<?php
require_once __DIR__ . '/../../config/config.php';
require_login();
$sid = current_student_id();
$pageTitle = 'AI study planner';
$activeNav = 'planner';

$sessions = $pdo->prepare("SELECT ss.*, c.name AS course_name FROM study_sessions ss
    JOIN courses c ON c.id=ss.course_id
    WHERE ss.student_id=? AND ss.source='ai_planner' AND ss.session_date >= CURDATE()
    ORDER BY ss.session_date ASC, ss.start_time ASC");
$sessions->execute([$sid]);
$sessions = $sessions->fetchAll();

// group by day for display
$byDay = [];
foreach ($sessions as $s) { $byDay[$s['session_date']][] = $s; }

include __DIR__ . '/../../includes/header.php';
?>
<div class="topline">
  <div><h1>AI study planner</h1><div class="desc">A personalised weekly timetable, generated from your deadlines and goals.</div></div>
  <form method="post" action="<?= BASE_URL ?>/student/planner/generate.php"><button class="pill-btn" type="submit">✨ Generate my week</button></form>
</div>

<?php if (!GEMINI_API_KEY): ?>
<div class="empty-note">Demo mode: no Gemini API key configured in <code>config/config.php</code>. The plan below is generated by a scheduling heuristic that runs entirely in PHP — add <code>GEMINI_API_KEY</code> to switch to live AI generation.</div>
<?php endif; ?>

<div class="card">
  <div class="block-head"><h3>Your upcoming plan</h3></div>
  <?php if ($byDay): foreach ($byDay as $date => $daySessions): ?>
    <div style="margin-bottom:16px;">
      <div class="mono" style="font-size:12px;color:var(--ink-soft);margin-bottom:8px;"><?= e(date('l, j F', strtotime($date))) ?></div>
      <?php foreach ($daySessions as $s): ?>
        <div class="item-row"><div class="item-dot" style="background:var(--amber);"></div>
          <div style="flex:1;"><div class="title"><?= e($s['focus_topic']) ?></div><div class="meta"><?= e($s['course_name']) ?> · <?= substr($s['start_time'],0,5) ?>–<?= substr($s['end_time'],0,5) ?></div></div>
        </div>
      <?php endforeach; ?>
    </div>
  <?php endforeach; else: ?>
    <div style="color:var(--ink-soft);font-size:13px;">No plan generated yet — click "Generate my week" above.</div>
  <?php endif; ?>
</div>
<?php include __DIR__ . '/../../includes/footer.php'; ?>
