-- =====================================================================
-- Smart Buddy Study Planner — Database Schema
-- Cavendish University Zambia — Final Year Project
-- Import this file in phpMyAdmin (XAMPP) or run: mysql -u root -p < smart_buddy.sql
--
-- This script is SAFE TO RE-RUN: it drops any existing smart_buddy
-- database first, so a full re-import always leaves you with a clean,
-- complete set of tables (fixes "table doesn't exist" errors caused by
-- a partial/interrupted previous import).
-- =====================================================================

DROP DATABASE IF EXISTS smart_buddy;
CREATE DATABASE smart_buddy CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE smart_buddy;

-- ---------------------------------------------------------------------
-- PROGRAMMES  (used by admin when adding a student)
-- ---------------------------------------------------------------------
CREATE TABLE programmes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    school VARCHAR(150) NOT NULL DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- ADMINS
-- ---------------------------------------------------------------------
CREATE TABLE admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- STUDENTS  (feature 1: registration, login, profile)
-- ---------------------------------------------------------------------
CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    programme_id INT NOT NULL,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    year_of_study TINYINT DEFAULT 1,
    added_by_admin TINYINT(1) DEFAULT 0,
    status ENUM('active','suspended') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (programme_id) REFERENCES programmes(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- PASSWORD RESETS  (feature 1: password reset)
-- ---------------------------------------------------------------------
CREATE TABLE password_resets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    token VARCHAR(100) NOT NULL,
    expires_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- COURSES  (feature 8: course management)
-- ---------------------------------------------------------------------
CREATE TABLE courses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    programme_id INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(20) NOT NULL,
    credit_hours TINYINT DEFAULT 3,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (programme_id) REFERENCES programmes(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Students enrol in courses; progress is tracked per student per course
CREATE TABLE student_courses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    course_id INT NOT NULL,
    progress_percent TINYINT DEFAULT 0,
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_enrolment (student_id, course_id),
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- ASSIGNMENTS & EXAMS  (feature 3)
-- ---------------------------------------------------------------------
CREATE TABLE assignments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    course_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    due_date DATE NOT NULL,
    status ENUM('pending','completed') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE exams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id INT NOT NULL,
    exam_date DATE NOT NULL,
    venue VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Study sessions — manually added, or generated by the AI planner
CREATE TABLE study_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    course_id INT NOT NULL,
    session_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    focus_topic VARCHAR(200),
    source ENUM('manual','ai_planner') DEFAULT 'manual',
    status ENUM('planned','completed','missed') DEFAULT 'planned',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- STUDY GROUPS  (feature 2)
-- ---------------------------------------------------------------------
CREATE TABLE study_groups (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE group_members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    group_id INT NOT NULL,
    student_id INT NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_membership (group_id, student_id),
    FOREIGN KEY (group_id) REFERENCES study_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE group_notes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    group_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    shared_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES study_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (shared_by) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE group_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    group_id INT NOT NULL,
    student_id INT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES study_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- NOTES  (feature 9)
-- ---------------------------------------------------------------------
CREATE TABLE notes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    course_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    youtube_link VARCHAR(255),
    file_path VARCHAR(255),
    is_practice_question TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- GOALS  (feature 7)
-- ---------------------------------------------------------------------
CREATE TABLE goals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    goal_type ENUM('weekly','monthly','semester') NOT NULL,
    title VARCHAR(200) NOT NULL,
    target_value DECIMAL(6,1) NOT NULL,
    current_value DECIMAL(6,1) DEFAULT 0,
    unit VARCHAR(30) DEFAULT 'units',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- NOTIFICATIONS  (feature 11)
-- ---------------------------------------------------------------------
CREATE TABLE notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    type VARCHAR(40) DEFAULT 'general',
    message VARCHAR(255) NOT NULL,
    is_read TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE notification_preferences (
    student_id INT PRIMARY KEY,
    push_enabled TINYINT(1) DEFAULT 1,
    email_enabled TINYINT(1) DEFAULT 1,
    deadline_alerts TINYINT(1) DEFAULT 1,
    exam_countdowns TINYINT(1) DEFAULT 1,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- AI CHAT LOG  (feature 5 — history for the study buddy chatbot)
-- ---------------------------------------------------------------------
CREATE TABLE chat_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    sender ENUM('student','buddy') NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =====================================================================
-- SEED DATA
-- =====================================================================

-- Real Cavendish University Zambia programme catalogue, grouped by its four Schools
-- (School of Business & IT, School of Law, School of Arts/Education/Social Sciences, School of Medicine).
-- Source: cavendishza.org/programmes/bachelors-degrees (current as of July 2026).
-- Row order matters: "Bachelor of Science in Computing" stays id=1 so the seeded demo
-- student and demo courses (which reference programme_id=1) remain valid.
INSERT INTO programmes (name, code, school) VALUES
('Bachelor of Science in Computing', 'BSCCOMP', 'School of Business and Information Technology'),
('Bachelor of Business Administration', 'BBA', 'School of Business and Information Technology'),
('Bachelor of Accounting', 'BAC', 'School of Business and Information Technology'),
('Bachelor of Arts - Banking and Finance', 'BABF', 'School of Business and Information Technology'),
('Bachelor of Arts - Purchasing and Supply', 'BAPS', 'School of Business and Information Technology'),
('Bachelor of Arts - Economics', 'BAECON', 'School of Business and Information Technology'),
('Bachelor of Science in Project Management', 'BSCPM', 'School of Business and Information Technology'),
('Bachelor of Science in Procurement and Supply Chain Management', 'BSCPSCM', 'School of Business and Information Technology'),
('Bachelor of Laws', 'LLB', 'School of Law'),
('Bachelor of Arts in Education - English and Civic Education', 'BAEEC', 'School of Arts, Education and Social Sciences'),
('Bachelor of Arts in Education - Mathematics and ICT', 'BAEMI', 'School of Arts, Education and Social Sciences'),
('Bachelor of Social Work', 'BSW', 'School of Arts, Education and Social Sciences'),
('Bachelor of Arts in Politics & International Relations', 'BAPIR', 'School of Arts, Education and Social Sciences'),
('Bachelor of Arts in Mass Communication and Public Relations', 'BMCPR', 'School of Arts, Education and Social Sciences'),
('Bachelor of Development Studies', 'BDS', 'School of Arts, Education and Social Sciences'),
('Bachelor of Clinical Sciences', 'BSCCS', 'School of Medicine'),
('Bachelor of Nursing and Midwifery Sciences', 'BNMWSC', 'School of Medicine'),
('Bachelor of Medicine & Bachelor of Surgery (MBChB)', 'MBCHB', 'School of Medicine'),
('Diploma in Registered Nursing', 'DRN', 'School of Medicine');

-- Default admin login: admin@cavendish.ac.zm / Admin@123
INSERT INTO admins (name, email, password_hash) VALUES
('System Administrator', 'admin@cavendish.ac.zm', '$2b$12$cmT7GOqbesjuif1i29c/0OYfBhOqbPyNinqKu70tSSjaSprteUaAK');

-- Default demo student login: chanda.mwansa@cavendish.ac.zm / Student@123
INSERT INTO students (programme_id, first_name, last_name, email, password_hash, year_of_study, added_by_admin) VALUES
(1, 'Chanda', 'Mwansa', 'chanda.mwansa@cavendish.ac.zm', '$2b$12$zT6MtydWDItCYVCGjfkGA.BGAFNJmf8ANe4k32q8S9PYWAMdI222.', 3, 0);

INSERT INTO courses (programme_id, name, code, credit_hours) VALUES
(1, 'Data Structures & Algorithms', 'CS301', 3),
(1, 'Database Systems', 'CS314', 3),
(1, 'Software Engineering', 'CS322', 3),
(1, 'Computer Networks', 'CS330', 3);

INSERT INTO student_courses (student_id, course_id, progress_percent) VALUES
(1, 1, 82), (1, 2, 58), (1, 3, 74), (1, 4, 66);

INSERT INTO assignments (student_id, course_id, title, due_date, status) VALUES
(1, 2, 'ER Diagram Submission', '2026-07-25', 'pending'),
(1, 1, 'Linked List Lab Report', '2026-07-27', 'pending'),
(1, 3, 'UML Use-Case Diagrams', '2026-08-02', 'pending'),
(1, 4, 'Subnetting Worksheet', '2026-08-05', 'pending'),
(1, 2, 'SQL Joins Exercise', '2026-07-20', 'completed');

INSERT INTO exams (course_id, exam_date, venue) VALUES
(2, '2026-08-04', 'Hall B'),
(1, '2026-08-10', 'Hall A'),
(4, '2026-08-14', 'Lab 3');

INSERT INTO goals (student_id, goal_type, title, target_value, current_value, unit) VALUES
(1, 'weekly', 'Study 20 hours this week', 20, 14.5, 'hrs'),
(1, 'weekly', 'Complete 3 practice quizzes', 3, 1, 'quizzes'),
(1, 'monthly', 'Finish Database Systems module 4', 4, 2, 'units'),
(1, 'semester', 'Maintain GPA above 3.5', 3.5, 3.6, 'GPA');

INSERT INTO notification_preferences (student_id) VALUES (1);

-- NOTE ON PASSWORDS:
-- The seeded password hashes above correspond to:
--   admin@cavendish.ac.zm       -> Admin@123
--   chanda.mwansa@cavendish.ac.zm -> Student@123
-- Always generate real hashes with PHP's password_hash() — never store plain text passwords.


-- Safe migration: adds the 'school' column to an existing programmes table
-- WITHOUT deleting any data. Run this in phpMyAdmin on your existing
-- smart_buddy database (select smart_buddy first, then go to the SQL tab
-- and paste this in, then click Go).

ALTER TABLE programmes ADD COLUMN school VARCHAR(150) NOT NULL DEFAULT '' AFTER code;

-- Fill in the correct School for each of Cavendish University Zambia's
-- real programmes. Anything not matched below is left blank and will show
-- under "Other programmes" until you edit it in the admin Programmes page.

UPDATE programmes SET school = 'School of Business and Information Technology'
WHERE code IN ('BSCCOMP','BBA','BAC','BABF','BAPS','BAECON','BSCPM','BSCPSCM');

UPDATE programmes SET school = 'School of Law'
WHERE code IN ('LLB');

UPDATE programmes SET school = 'School of Arts, Education and Social Sciences'
WHERE code IN ('BAEEC','BAEMI','BSW','BAPIR','BMCPR','BDS');

UPDATE programmes SET school = 'School of Medicine'
WHERE code IN ('BSCCS','BNMWSC','MBCHB','DRN');

-- If your existing programmes table still has the old placeholder codes
-- (BSCCS/BSCIT/BSCSE from before the real CUZ catalogue was added), this
-- assigns them to Business & IT so the page still works; rename/replace
-- them in the admin UI whenever convenient.
UPDATE programmes SET school = 'School of Business and Information Technology'
WHERE code IN ('BSCIT','BSCSE') AND school = '';

-- Safe migration: adds file-sharing columns to the existing group_notes table

ALTER TABLE group_notes
    ADD COLUMN file_path VARCHAR(255) DEFAULT NULL AFTER shared_by,
    ADD COLUMN file_name VARCHAR(255) DEFAULT NULL AFTER file_path,
    ADD COLUMN file_type VARCHAR(10) DEFAULT NULL AFTER file_name;


-- Safe migration for the Announcements feature. Run in phpMyAdmin's SQL tab
-- on the smart_buddy database. Does NOT delete any existing data.

ALTER TABLE students ADD COLUMN semester TINYINT DEFAULT 1 AFTER year_of_study;

CREATE TABLE IF NOT EXISTS announcements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    programme_id INT DEFAULT NULL,
    year_of_study TINYINT DEFAULT NULL,
    semester TINYINT DEFAULT NULL,
    recipient_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE,
    FOREIGN KEY (programme_id) REFERENCES programmes(id) ON DELETE CASCADE
) ENGINE=InnoDB;